theme: jekyll-theme-primer
title: jorsh.xyz wiki
url: "https://jorsh.xyz/wiki/"
baseurl: "/wiki/"
plugins:
  - jekyll-sitemap
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
